# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curs', models.CharField(max_length=50)),
                ('sigla_curs', models.CharField(max_length=10)),
                ('grau_curs', models.CharField(max_length=20)),
                ('autorizacao_reconhecimento_curs', models.CharField(max_length=30)),
                ('duracao_curs', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faculdade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_facu', models.CharField(max_length=100)),
                ('sigla_facu', models.CharField(max_length=20)),
                ('n0800_facu', models.CharField(max_length=20)),
                ('endereco_facu', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='id_facu_curs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Faculdade'),
        ),
    ]
